# Generated by Django 5.2 on 2025-05-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('power_rating', models.FloatField(help_text='Power rating in watts')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consumption_kwh', models.FloatField(help_text='Energy consumption in kWh')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='users.appliance')),
            ],
        ),
    ]
