# Generated by Django 5.2 on 2025-05-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_prediction_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='days_used_per_week',
            field=models.PositiveIntegerField(default=7, help_text='Number of days appliance is used per week'),
        ),
    ]
