# Generated by Django 5.2 on 2025-05-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appliance_days_used_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='usage_time',
            field=models.FloatField(default=1.0, help_text='Daily usage time in hours'),
        ),
    ]
