# Generated by Django 5.2 on 2026-07-02 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appliance_usage_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energyconsumption',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'ordering': ['-predicted_date']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date']},
        ),
        migrations.AddField(
            model_name='appliance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='energyconsumption',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prediction',
            name='anomaly_score',
            field=models.FloatField(default=0.0, help_text='Anomaly severity index (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='confidence_score',
            field=models.FloatField(default=0.95, help_text='AI Model Confidence Score'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediction',
            name='recommendation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='co2_emissions_kg',
            field=models.FloatField(default=0.0, help_text='Carbon emissions in kg'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='peak_usage_kwh',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='savings_amount',
            field=models.FloatField(default=0.0, help_text='Estimated savings in currency'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predicted_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='efficiency',
            field=models.FloatField(help_text='Efficiency percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='physical_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='energyconsumption',
            index=models.Index(fields=['appliance', 'date'], name='users_energ_applian_c64d89_idx'),
        ),
    ]
